name: 'setup-k8s-action'
description: 'Setup k8s tools, config and populate KUBECONFIG env variable'
inputs:
  environment:
    required: true
    description: the environment to deploy to
    default: staging
  config-production:
    required: true
    description: k8s configuration for production
  config-staging:
    required: true
    description: k8s configuration for staging
  location:
    default: .kube/config
    description: The location of the config
runs:
  using: "composite"
  steps:
  - shell: bash
    run: |
      echo "Unknown environment: ${{ inputs.environment }}"
      exit 1
    if: (inputs.environment != 'production' && inputs.environment != 'staging')
  - uses: yokawasa/action-setup-kube-tools@v0.11.2
    with:
      kubectl: '1.27.5'
      # supports env vars > to secrets/configs
      kustomize: '4.5.7'
      setup-tools: |
        kubectl
        kustomize
        kubeconform
        helm
  - run: mkdir -p .kube
    shell: bash
  - run: 'echo "${{ inputs.config-production }}" > ${{ inputs.location }}'
    if: inputs.environment == 'production'
    shell: bash
  - run: 'echo "${{ inputs.config-staging }}" > ${{ inputs.location }}'
    if: inputs.environment == 'staging'
    shell: bash
  - run: echo 'KUBECONFIG=${{ inputs.location }}' >> $GITHUB_ENV
    shell: bash
  - run: cat $KUBECONFIG
    shell: bash
